[package]
name = "udpt-rs"
version = "3.0.0-alpha"
authors = ["Naim A. <naim94a@github.com>"]
description = "High performance torrent tracker"

[profile.release]
lto = "thin"

[dependencies]
serde = "1.0.80"
mongodb = "v0.3.12"
bincode = "1.0.1"
serde_derive = "1.0.80"
actix-web = "0.7.16"
actix-net = "0.2.5"
binascii = "0.1.2"
toml = "0.4.8"
clap = "2.32.0"
log = "0.4.5"
fern = "0.5.6"
num_cpus = "1.8.0"
serde_json = "1.0.32"
bzip2 = "0.3.3"
futures = "0.1.25"
lazy_static = "1.2.0"
